import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Canvasbox from "@/components/Canvasbox";
import Navbar from "@/components/Navbar";

const GravitasBold = localFont({
  src: "./fonts/Studio K - Gravitas Bold.otf",
  variable: "--font-geist-sans",

});
const Gravitas = localFont({
  src: "./fonts/Studio K - Gravitas.otf",
  variable: "--font-geist-mono",
 
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <>
      <main className={ ` ${styles.main} ${Gravitas.variable} ${GravitasBold.variable}`}>

     <Canvasbox/>
     </main>
      </>
    </>
  );
}
